FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

RUN wget https://github.com/tinygo-org/tinygo/releases/download/v0.32.0/tinygo_0.32.0_amd64.deb && \
sudo dpkg -i tinygo_0.32.0_amd64.deb && \
rm -f tinygo_0.32.0_amd64.deb