name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up packages
        run: |
          sudo apt-get update
          sudo apt-get -y install libpcap-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - name: Run tests
        run: |
          make -j test
          make -j test-third-party
